### ISSUE TITLE
the download link said page not find 

### ISSUE THREAD

**Issue by ghost** [the-synister/the-source#2]
i go to https://the-synister.github.io/#download
and click the download....but page not find

**Comment by juanecabellob** [comment]
Which OS do you have? I cannot reproduce it

**Comment by RyanHerbert** [comment]
It looks like the link is broken on Windows.  

The download link is pointing to: 
https://github.com/the-synister/the-source/releases/download/release1-0-2/synister-Win-1.0.2.exe

**Comment by juanecabellob** [comment]
it is now fixed. can you try again?

**Comment by RyanHerbert** [comment]
Looks to be good.

**Comment by juanecabellob** [comment]
perfect! Thanks! I'm closing it then

**Comment by ghost** [comment]
Oh, it is ok now, thanks

juanecabellob 於 20/3/2016 1:02 寫道:
