### ISSUE TITLE
Saving files as mp3 or wav

### ISSUE THREAD

**Issue by MissDomino** [the-synister/the-source#27]
Synister is fantastic but it only seems to allow saving audio files as xml. How do you save as mp3 or wav, or how do you convert/export xml files into mp3 or wav? I can't open my files into any other programme, and they are therefore unusable for my film projects at the moment. Thanks.

**Comment by juanecabellob** [comment]
Hi @MissDomino. Synister is meant to be used in a DAW like Ableton as a plugin. The standalone only saves the presets with which you can create the sounds you wish but not the music itself. To save songs you create with synister you need a DAW program.
