### ISSUE TITLE
Synister actually works in Linux...

### ISSUE THREAD

**Issue by MarkkuMyllymaki** [the-synister/the-source#4]
I just thought you could add a note to webpage, that at least 32-bit Synister works in 32-bit Linux via Wine. UI works, presets can be loaded, sound works (even if existing presets are VERY basic).

**Comment by davephillips** [comment]
It builds for Linux as a native VST plugin. Takes a little work but it can be done.

**Comment by juanecabellob** [comment]
thanks for pointing out! we are continuing this issue into #5. We are looking into expanding our support to Linux as well!
